Traceback (most recent call last):
  File "<string>", line 3, in <module>
RuntimeError: NVML_SUCCESS == r INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1708025847130/work/c10/cuda/CUDACachingAllocator.cpp":830, please report a bug to PyTorch. 
